routes = [{'app_name': 'default',
           'route_path': '/default',
           'request_method': 1,
           'file_path': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/default/base/templates/index.html',
           'context': {'title': 'default',
                       'app_name': 'default'},
           'html_templates': {'head': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/head.html',
                              'content': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/default/base/templates/index.html',
                              'foot': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/foot.html'}},
          {'app_name': 'default',
           'route_path': '/',
           'request_method': 1,
           'file_path': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/default/base/templates/index.html',
           'context': {'title': 'Default',
                       'app_name': 'default'},
           'html_templates': {'head': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/head.html',
                              'content': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/default/base/templates/index.html',
                              'foot': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/foot.html'}},
          {'app_name': 'default',
           'route_path': '/',
           'request_method': 2,
           'file_path': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/default/base/templates/index.html',
           'context': {'title': 'Default',
                       'app_name': 'default'},
           'html_templates': {'head': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/head.html',
                              'content': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/default/base/templates/index.html',
                              'foot': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/foot.html'},
           'request_function': 'default_post'},
          {'app_name': 'admin',
           'route_path': '/admin',
           'request_method': 1,
           'file_path': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/admin/base/templates/index.html',
           'context': {'title': 'admin',
                       'app_name': 'admin',
                       'users': [(1,
                                  'Justin',
                                  'Turney',
                                  'justinclarkturney@gmail.com',
                                  '4172309931',
                                  'jturney',
                                  0,
                                  0),
                                 (2,
                                  'Debo',
                                  'Brown',
                                  'H@ell.com',
                                  '4',
                                  'ju',
                                  0,
                                  0),
                                 (3,
                                  'Jerry',
                                  'Fallwell',
                                  't@A',
                                  '333',
                                  'h',
                                  0,
                                  0),
                                 (4,
                                  'Another',
                                  'Test',
                                  't@h',
                                  '45',
                                  'h',
                                  0,
                                  0)]},
           'html_templates': {'head': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/head.html',
                              'content': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/admin/base/templates/index.html',
                              'foot': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/foot.html'}},
          {'app_name': 'profile',
           'route_path': '/profile',
           'request_method': 1,
           'file_path': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/profile/base/templates/index.html',
           'context': {'title': 'profile',
                       'app_name': 'profile'},
           'html_templates': {'head': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/head.html',
                              'content': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/profile/base/templates/index.html',
                              'foot': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/foot.html'}},
          {'app_name': 'profile',
           'route_path': '/profile/register',
           'request_method': 1,
           'file_path': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/profile/base/templates/register.html',
           'context': {'title': 'Default',
                       'app_name': 'profile'},
           'html_templates': {'head': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/head.html',
                              'content': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/profile/base/templates/index.html',
                              'foot': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/foot.html'}},
          {'app_name': 'profile',
           'route_path': '/profile/register',
           'request_method': 2,
           'file_path': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/profile/base/templates/register.html',
           'context': {'title': 'Default',
                       'app_name': 'profile'},
           'html_templates': {'head': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/head.html',
                              'content': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/profile/base/templates/index.html',
                              'foot': 'C:\\Users\\jturney\\PycharmProjects\\NAPyF/global_static/templates/foot.html'},
           'request_function': 'auth_post_user',
           'redirect': '/profile'}]
